-- GENERATED by audit/capture_oracle.py — DO NOT EDIT.
-- Frozen under MANIFEST.sha256. Every constant below is a measured
-- anchor from the Python oracle (proplang.py / tests_acceptance.py),
-- captured at full repr precision; provenance on each definition.
--
-- TOLERANCE PROTOCOL (frozen): counts, actions, tick counts and
-- rendered programs are asserted EXACTLY; probabilities and
-- entropies within tolProb; cumulative log-losses within tolBits.
-- A Phase-2 failure of any pinned anchor is stop-and-report and a
-- human-signed Phase-1 re-open; tolerances are part of the oracle
-- and are never widened in place.
module Anchors where

-- absolute tolerance for probabilities and entropies (bits)
tolProb :: Double
tolProb = 1e-6

-- absolute tolerance for cumulative log-losses (bits)
tolBits :: Double
tolBits = 1e-4

-- TEST 1 — the changing-world test ----------------------------------

-- (t, P(y=1), action, meta-entropy bits) at the printed probe ticks
-- (t mod 20 == 0 or even t in [58,76]); from the timeline loop of
-- tests_acceptance.test_changing_world.
t1ProbeRows :: [(Int, Double, String, Double)]
t1ProbeRows =
  [ (0, 0.5, "consult", 4.218680167152279)
  , (20, 0.7801612210090821, "predict1", 3.6808103294273944)
  , (40, 0.817086962227911, "predict1", 3.3680483722040315)
  , (58, 0.8167987013315117, "predict1", 3.208714500907728)
  , (60, 0.8317096435049672, "predict1", 3.0908584386540268)
  , (62, 0.7997673047087186, "predict1", 3.289339688780028)
  , (64, 0.680841744916563, "predict1", 3.70758906775785)
  , (66, 0.4794419394807554, "consult", 3.9528542433140568)
  , (68, 0.5084253998509259, "consult", 3.8532927457817983)
  , (70, 0.3523403895165587, "consult", 3.8068768765414327)
  , (72, 0.2557367127315604, "predict0", 3.5913538005366594)
  , (74, 0.20386082032772884, "predict0", 3.339974424830039)
  , (76, 0.17513975301406776, "predict0", 3.1014182147550686)
  , (80, 0.14545760077036576, "predict0", 2.6739616202997207)
  , (100, 0.1252959540465336, "predict0", 2.0212022603721023)
  , (120, 0.10190582168873936, "predict0", 1.142017100540206)
  , (140, 0.1019416004873956, "predict0", 1.1235985548610419)
  ]

-- every tick whose chosen action is consult (exact; min argmax
-- margin over the whole run is ~1.2e-2, far above float noise)
t1ConsultTicks :: [Int]
t1ConsultTicks = [0,1,3,4,65,66,67,68,69,70]

-- meta-entropy at t=59 (timeline[59]) and max over t in [60,90)
t1HPre, t1HPostMax :: Double
t1HPre = 3.1489671033557265
t1HPostMax = 3.9528542433140568

-- agent.meta.top(1) after 160 ticks: the exact change-point sentence
-- (tau grid index 11 = 60) and its posterior
t1MapProgram :: String
t1MapProgram = "('bern', ('if', ('>', ('get', 't'), ('c', 'tau', 11)), ('c', 'theta', 0), ('c', 'theta', 8)))"

t1MapPosterior :: Double
t1MapPosterior = 0.6383157408996493

-- TEST 2 — the lazy-genius test -------------------------------------

-- (world price of a tick, thinking ticks, final act), from
-- tests_acceptance.run_deliberation on the seed-14 buffer; ticks and
-- final act asserted EXACTLY (min |v_act - v_think| margin 1.5e-3)
t2Rows :: [(Double, Int, String)]
t2Rows =
  [ (0.3, 1, "L")
  , (0.05, 3, "L")
  , (0.005, 12, "L")
  , (0.0, 12, "L")
  ]

-- TEST 3 — the forgetting-factor trap -------------------------------

-- (gamma, drift-world log-loss, stationary log-loss) for the
-- quarantined Beta tracker, tests_acceptance.forgetter_logloss
t3ForgetterRows :: [(Double, Double, Double)]
t3ForgetterRows =
  [ (0.8, 369.7929712967316, 396.60210068705993)
  , (0.9, 345.5037265510021, 370.0335776855678)
  , (0.95, 340.88263044835253, 359.3527535371701)
  , (0.98, 348.93795719904125, 353.28252431117664)
  , (1.0, 397.9262111919014, 350.33027664041333)
  ]

-- tests_acceptance.agent_logloss over drift400 / flat400
t3AgentDrift, t3AgentFlat :: Double
t3AgentDrift = 339.7824236038744
t3AgentFlat = 351.1061771452692

-- the agent's MAP program on the drifting world: drift rate 0.1
-- inferred as CONTENT (rho grid index 3)
t3MapProgram :: String
t3MapProgram = "('hmm', ('c', 'rho', 3))"

-- TEST 4 — the deletion audit ---------------------------------------

-- cumulative predictive log-loss (bits) on the shifted world:
-- frozen agent (cond deleted; exactly 160.0 — the enumeration is
-- symmetric under theta <-> 1-theta so the prior predictive is
-- exactly 1/2 every tick), full grammar, no-if, no-get
t4LlFrozen, t4LlFull, t4LlNoif, t4LlNoget :: Double
t4LlFrozen = 160.00000000000003
t4LlFull = 96.682771822417
t4LlNoif = 103.44568113917315
t4LlNoget = 103.44568113917315

-- drifting world (250 ticks = drift400 prefix): full grammar vs
-- hmm/rw deleted
t4LlFullD, t4LlNohmm :: Double
t4LlFullD = 207.09758316305718
t4LlNohmm = 211.05494026245512

-- enumeration counts: full grammar; c (grids) deleted; bern deleted
t4NFull, t4NNoc, t4NNobern :: Int
t4NFull = 1169
t4NNoc = 0
t4NNobern = 0
