#!/usr/bin/env python3
# test-stream fixture generator (step 6, the g4Self return — ruling
# D-b6). Descendant of test-membrane/gen_fixtures.py's role: seeds
# inline, streams printed as Haskell lists, correlation sanity-checks
# printed beside them. The ENGINE-level sanity simulation (MAP mentions
# the action name; the control hands the MAP to the changepoint story)
# is the overlay satisfiability transcript's job (R-D21) — this script
# checks the world's own arithmetic, and per the probe-discipline
# clause it declares no value an import could supply (the control
# stream is the frozen test/Streams.hs shifted160, imported by the
# oracle, never regenerated here).
#
# The C-world, re-declared with its action in the stream (no lag):
#   features per tick: [("t", t), ("z", zC !! t)]
#   menu (constant):   [("a", grid 0.5 :| [1.5])]   -- wait = 0.5
#   scripted pilot:    a = 1.5 when z > 0.5 else 0.5 (the test's claim
#                      is the posterior's, not the policy's)
#   evidence (self world): y ~ Bern(0.85) when a = 1.5, Bern(0.15)
#                      when a = 0.5 — y is explained by the CURRENT
#                      tick's action, which only a step-6 agent can see
#   evidence (control):    the frozen shifted160 (imported)
# z is drawn so the action is NOT a simple function of t (irregular
# threshold crossings), else t-guards would explain y as well as
# a-guards and the self-signature claim would be vacuous.

import random

N = 160
rng = random.Random(20260716)

zC = [round(rng.random(), 3) for _ in range(N)]
act = [1.5 if z > 0.5 else 0.5 for z in zC]
yS = [1 if rng.random() < (0.85 if a == 1.5 else 0.15) else 0
      for a in act]

n_hi = sum(1 for a in act if a == 1.5)
y_given_hi = sum(y for y, a in zip(yS, act) if a == 1.5) / n_hi
y_given_lo = sum(y for y, a in zip(yS, act) if a == 0.5) / (N - n_hi)

# the action must not be a cheap function of time: count threshold
# crossings (a changepoint story needs few; the z-driven action has
# many)
crossings = sum(1 for i in range(1, N) if act[i] != act[i - 1])

# g2's action-responsive streams (drawn AFTER zC/ySelf so those are
# byte-stable): the world answers y from the PREVIOUS tick's action —
# yHi when the agent acted, yLo when it waited.
yHi = [1 if rng.random() < 0.9 else 0 for _ in range(N)]
yLo = [1 if rng.random() < 0.1 else 0 for _ in range(N)]

def hs_list(name, ty, xs):
    print(f"{name} :: [{ty}]")
    print(f"{name} =")
    for i in range(0, len(xs), 10):
        chunk = ", ".join(str(x) for x in xs[i:i + 10])
        lead = "  [ " if i == 0 else "  , "
        print(lead + chunk)
    print("  ]")
    print()

print(f"-- generated by test-stream/gen_fixtures.py (seed 20260716 inline)")
print(f"-- sanity: n(a=1.5)={n_hi}/160, P(y=1|a=1.5)={y_given_hi:.3f},"
      f" P(y=1|a=0.5)={y_given_lo:.3f}, action crossings={crossings}")
print()
hs_list("zC", "Double", zC)
hs_list("ySelf", "Int", yS)
hs_list("yHi", "Int", yHi)
hs_list("yLo", "Int", yLo)
