#!/usr/bin/env python3
"""Generate bench/P2Real.hs from life-agent's OWN world declaration.

THE ONE-GENERATOR LAW (CLAUDE.md, canonized at breadth-freeze-r0): any two
artefacts required to agree share ONE generator, or one DERIVES from the other
and ASSERTS the derivation at run time -- never two hand-maintained copies.

The bench's P2real profile and the consumer's shipped hello are exactly such a
pair.  This script is the single generator: it imports life-agent's
`membrane.world.handshake_decl` and emits the Haskell literals.  Nothing here
is hand-transcribed, so nothing here can go stale silently -- and BenchLib
asserts the derivation at run time by reading `models` back off the wire.

THE GENERATOR EXEMPTION (CLAUDE.md, exact-freeze-r0): a generator of frozen
data is not a prototype; it lands in-tree with the artifact it generates, and
regenerating the artifact from it is a standing identity row.  Re-run:

    python3 bench/gen-p2real.py --check    # identity row: regenerate + diff
    python3 bench/gen-p2real.py            # rewrite bench/P2Real.hs

Provenance of the declaration itself: life-agent @ ebc5941,
src/life_agent/membrane/world.py, the binding `handshake_decl`.
"""
import argparse, json, pathlib, re, subprocess, sys

LIFE_AGENT = pathlib.Path.home() / "git" / "life-agent"
OUT = pathlib.Path(__file__).resolve().parent / "P2Real.hs"


def declaration():
    sys.path.insert(0, str(LIFE_AGENT / "src"))
    from life_agent.membrane import world as W          # noqa: E402
    head = subprocess.run(["git", "-C", str(LIFE_AGENT), "rev-parse", "HEAD"],
                          capture_output=True, text=True, check=True).stdout.strip()
    return W.handshake_decl({}), head, W


def hs_double(x: float) -> str:
    # `repr` is Python's shortest round-tripping form; Haskell's `read` accepts
    # it for Double, and both sides then embed by the SAME realToFrac path the
    # bench's rD/emb pair already uses.  A value that is not exactly
    # representable stays inexact identically on both sides.
    s = repr(float(x))
    return f"({s})" if s.startswith("-") else s


def hs_list_d(xs) -> str:
    return "[" + ", ".join(hs_double(x) for x in xs) + "]"


def hs_str(s: str) -> str:
    return json.dumps(s)


def hs_list_s(xs) -> str:
    return "[" + ", ".join(hs_str(x) for x in xs) + "]"


def render(decl, head, W) -> str:
    w = decl["world"]
    ns = w["namespace"]
    guards = [(g["name"], g["grid"]) for g in w["guards"]]
    menu = w["menu"][0]
    theta = w["codebooks"]["theta"]
    rho = w["codebooks"].get("rho")
    clock = (w["clock"][0] if w.get("clock") else None)
    arity = w.get("obs_arity")
    said = w["utility"]["said"]

    G = sum(len(g) for _, g in guards)
    n = len(theta)
    nr = len(rho) if rho else 0
    K = arity if arity else 2
    models = (K - 1) * (n + nr + G * n * (n - 1))

    fams = {}
    for name in W.indicator_names():
        fams.setdefault(name.split("=")[0], []).append(name)

    ns_lit = hs_list_s(ns)
    guards_lit = "\n  , ".join(f"({hs_str(nm)}, {hs_list_d(g)})" for nm, g in guards)
    theta_lit = hs_list_d(theta)
    rho_lit = ("Just " + hs_list_d(rho)) if rho else "Nothing"
    arity_lit = f"Just {arity}" if arity else "Nothing"
    arity_note = "declared" if arity else "ABSENT (K = 2 by default)"
    clock_lit = ("Nothing" if not clock else
                 f'Just ({hs_str(clock["name"])}, {hs_double(clock["price"])}, {clock["batch"]})')
    said_lit = hs_str(json.dumps(said, separators=(", ", ": ")))
    fams_lit = "\n  , ".join(f"({hs_str(k)}, {hs_list_s(v)})" for k, v in fams.items())
    flags_lit = hs_list_s([f for v in fams.values() if len(v) == 1 for f in v])
    op_rate = hs_double(W.OPERATING_RATE)

    def _mid(bucket: str) -> float:
        nums = [int(x) / 100.0 for x in re.findall(r"\d+", bucket)]
        if bucket.startswith("lt"):
            return round(nums[0] / 2, 4)
        if bucket.startswith("ge"):
            return round((nums[0] + 1.0) / 2, 4)
        return round(sum(nums) / len(nums), 4)

    cred = [(nm, _mid(nm.split("=", 1)[1]))
            for nm in fams.get("leader-credence", [])]
    cred_lit = "\n  , ".join(f"({hs_str(nm)}, {hs_double(r)})" for nm, r in cred)

    n_menu = len(menu["grid"])
    n_guards = len(guards)
    n_ns = len(ns)
    menu_lit = f'({hs_str(menu["name"])}, {hs_list_d(menu["grid"])})'
    menu_name = menu["name"]

    return f"""-- GENERATED BY bench/gen-p2real.py -- DO NOT EDIT BY HAND.
--
-- The consumer's ACTUAL membrane world declaration, read out of life-agent's
-- own code (@ {head}, src/life_agent/membrane/world.py, the binding
-- `handshake_decl`).  The bench's P2 profile was a RECONSTRUCTION built from
-- a table that carried merge orders rather than arities; this module is the
-- real declaration, so the reconstruction's four structural errors
-- (namespace 3 vs {n_ns}, guard mass 6 vs {G}, dyadic theta vs {n}
-- NON-dyadic decimals, a declared walk family vs none) cannot recur.
--
-- Regenerate, and assert the identity, with:
--     python3 bench/gen-p2real.py --check
--
-- Population the enumerator predicts for this declaration:
--     models = (K-1) * (n_theta + n_rho + G * n_theta * (n_theta - 1))
--            = ({K}-1) * ({n} + {nr} + {G} * {n} * {n - 1})
--            = {models}
-- BenchLib ASSERTS this against the host's own hello reply at run time; the
-- derivation is never trusted, only checked.
module P2Real
  ( p2realNs, p2realGuards, p2realMenu, p2realTheta, p2realRho
  , p2realArity, p2realClock, p2realSaid, p2realModels
  , p2realFamilies, p2realFlags, p2realProvenance
  , p2realOperatingRate, p2realCredenceRates
  ) where

-- | life-agent commit the declaration was read from.
p2realProvenance :: String
p2realProvenance = {hs_str(head)}

-- | The full declared namespace, in declaration order ({n_ns} names).  `t`
--   (the evidence-stream index) is first and the ONE writable name
--   `{menu_name}` is last; those two are exactly the names carrying NO guard
--   row (life-agent r43's census over all {n_ns} names).
p2realNs :: [String]
p2realNs = {ns_lit}

-- | {n_guards} guard rows, one per indicator, every grid arity 1.
p2realGuards :: [(String, [Double])]
p2realGuards =
  [ {guards_lit}
  ]

-- | The menu: one writable name, {n_menu} affordances.  Grid ORDER IS
--   NORMATIVE -- `wait` is every name at its grid's FIRST point and CL-3
--   resolves ties first-listed, so the safe act sits at the head.
p2realMenu :: (String, [Double])
p2realMenu = {menu_lit}

-- | codebooks.theta -- {n} points from the consumer's FROZEN RULE (the union
--   of the measured operating rate, every argmax crossing, the recorded
--   shadow's p05/median/p95, and the endpoints).  NOT dyadic: every rung
--   embeds as a 2^-55-denominator rational, which is the bench's own
--   highest-ranked cost lever -- and the reconstruction had it backwards.
p2realTheta :: [Double]
p2realTheta = {theta_lit}

-- | codebooks.rho -- ABSENT.  The consumer declares NO walk family, so the
--   reconstruction's 78%-of-tick walk attribution has no counterpart here.
p2realRho :: Maybe [Double]
p2realRho = {rho_lit}

-- | obs_arity -- {arity_note}.
p2realArity :: Maybe Int
p2realArity = {arity_lit}

-- | The clock row: the consumer DOES declare one, and its price is DERIVED
--   to be unreachable ((max u - min u) + 1), not tuned.  This is the row
--   that routes selection through policyPick -- OB-24's remedy -- and it is
--   why every decide pays a preposterior it can never use (issue #24).
p2realClock :: Maybe (String, Double, Int)
p2realClock = {clock_lit}

-- | The said@1 utility sentence, verbatim from the consumer's hello:
--   {n_menu} linear arms under nested `if`s on ["get","{menu_name}"].
p2realSaid :: String
p2realSaid = {said_lit}

-- | The population the enumerator predicts; asserted against the wire.
p2realModels :: Int
p2realModels = {models}

-- | Indicator families (name prefix -> member names).  The feature process
--   picks exactly one member per family, which is how the consumer's
--   indicators are actually built.
p2realFamilies :: [(String, [String])]
p2realFamilies =
  [ {fams_lit}
  ]

-- | Standalone binary flags (families of one, set independently).
p2realFlags :: [String]
p2realFlags = {flags_lit}

-- | The consumer's MEASURED y=1 rate, imported from its own module-level
--   constant `OPERATING_RATE` (world.py) rather than re-declared here --
--   the probe-discipline law: a probe reads declared data and never
--   re-declares a value it could import (the tauPoints incident).
p2realOperatingRate :: Double
p2realOperatingRate = {op_rate}

-- | Emission rate per leader-credence bucket, DERIVED FROM THE BUCKET NAMES
--   (`lt50`, `50to70`, ... are declared percentage bounds; each rate is the
--   bound-midpoint).  The bench needs a generative rate per context and the
--   consumer declares none, so this is the bench's own choice -- but it is
--   derived from declared names rather than invented, and the bucket MIX is
--   uniform here, which the consumer's real traffic is not.  Recorded as a
--   deviation; it moves which hypotheses survive, not the fold's cost, since
--   nothing prunes the {models}-model population.
p2realCredenceRates :: [(String, Double)]
p2realCredenceRates =
  [ {cred_lit}
  ]
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff against the in-tree file (the identity row)")
    a = ap.parse_args()
    decl, head, W = declaration()
    text = render(decl, head, W)
    if a.check:
        cur = OUT.read_text() if OUT.exists() else ""
        if cur == text:
            print(f"IDENTITY OK  {OUT.name} regenerates byte-identical from life-agent @ {head}")
            return 0
        print(f"IDENTITY FAIL {OUT.name} differs from its generator's output", file=sys.stderr)
        import difflib
        sys.stderr.writelines(difflib.unified_diff(
            cur.splitlines(True), text.splitlines(True), "in-tree", "generated"))
        return 1
    OUT.write_text(text)
    print(f"wrote {OUT}  (life-agent @ {head})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
